# Generated by Django 4.2.7 on 2025-03-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GLCode',
            fields=[
                ('gl_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gl_description', models.CharField(max_length=255)),
                ('limit_in_millions', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('limit_utilized', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance_available', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wing_division', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utilized_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gl_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.glcode')),
            ],
        ),
        migrations.CreateModel(
            name='SubHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.head')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Account', 'Account'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withholding_sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withholding_income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.branch')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.costcenter')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.head')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.region')),
                ('sub_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.subhead')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.region'),
        ),
    ]
