# Generated by Django 4.2.7 on 2025-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gl_code',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='cnic',
            new_name='ntn',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='head',
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AllowanceRequest',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
