# Generated by Django 4.2.7 on 2025-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]