# Generated by Django 4.2.7 on 2025-04-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_employee_account_name_employee_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gl_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.glcode'),
        ),
    ]
