# Generated by Django 4.2.7 on 2025-04-09 17:06

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('expenses', '0002_add_account_fields'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='allowancerequest',
#             name='approval_reason',
#             field=models.TextField(blank=True, null=True),
#         ),
#     ]
# Generated by Django 4.2.7 on 2025-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_employee_account_name_employee_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]