# Generated by Django 4.2.7 on 2025-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_user_account_name_user_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancerequest',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
