# Generated by Django 4.2.7 on 2025-04-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_gl_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='division',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='wing',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='gl_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.glcode'),
        ),
    ]
