# Generated by Django 4.2.7 on 2025-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_allowancerequest_approval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Government', 'Government')], max_length=50, null=True),
        ),
    ]
