# Generated by Django 4.2.7 on 2025-04-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_division_expense_wing_alter_expense_gl_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='gl_code',
        ),
    ]
