# Generated by Django 4.2.7 on 2025-04-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_populate_gl_code'),
        ('expenses', '0005_remove_expense_gl_code'),
    ]

    operations = [
    ]
