# Generated by Django 4.2.7 on 2025-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_merge_20250415_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Internet', 'Internet'), ('Office Supplies', 'Office Supplies')], default='General', max_length=50),
        ),
    ]
