# Generated by Django 4.2.7 on 2025-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_cadre_employeetype_employee_cadre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
