# Generated by Django 4.2.7 on 2025-04-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_vendor_account_number_vendor_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostCenter',
        ),
    ]
