# Generated by Django 4.2.7 on 2025-04-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_branch_division_wing_remove_employee_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
