# Generated by Django 4.2.7 on 2025-05-01 15:12

from django.db import migrations, models
from django.db import connection


def table_exists(table_name):
    """Check if a table exists in the database"""
    with connection.cursor() as cursor:
        tables = connection.introspection.table_names()
        return table_name in tables


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_add_budget_fields_to_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
    
    # Only add the DeleteModel operation if the table exists
    if table_exists('expenses_subhead'):
        operations.append(
            migrations.DeleteModel(
                name='SubHead',
            )
        )
