# Generated by Django 4.2.7 on 2025-05-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_rename_fasical_to_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.glcode'),
        ),
        # Removed the DeleteModel operation since the table doesn't exist
    ]